### ISSUE TITLE
Allow using any of the listed servers in api docu/spec

### ISSUE THREAD

**Issue by embix** [dotnet/HttpRepl#445]
We currently have a service returning multiple servers

```yaml
servers:
  - url: https://staging.api.company.com
    description: staging (always requires auth)
  - url: https://localhost:5001/
    description: local dev/test server with tls
  - url: http://localhost:5000/
    description: local dev/test server
```

If I connect to localhost:5001 it retrieves the swagger/openapi and uses staging instead of the instance wanted to connected to. It seems like `httprepl` always uses the first server. Is there any way we can make it use another one?

**Comment by tlmii** [comment]
If you specify the base url explicitly in the connect command (using the `--base` option in addition to the other arguments and options you were specifying) that will force the tool to accept that as your base and ignore what is specified in the servers array in the OpenAPI description document.

That said, we should probably go ahead and add the ability to do that some other way - by index during connect or by another command after connect has occurred.

**Comment by tlmii** [comment]
@bradygaster This is something I'd be curious about your thoughts on from a UX perspective - since the servers are only identified by a url (and implicitly by index), what would be the correct experience for a user to specify? It sort of seems like the `--base` is already the right experience, though maybe we need to bring back the `set base` command in another form to be able to switch between servers quickly. 

Thoughts?

**Comment by bradygaster** [comment]
Curious what @embix would say if we implied his YAML island above required a `tag`-like property that would make it easier. Sure, `set base` would be good as a bring-back, but I wonder if @embix or others would like the idea of having an API with multiple environments (localhost, dev, staging, qa, etc.) that they could test using something like a switch. So maybe we extend on @embix's YAML from above:

```yaml
servers:
  - url: https://staging.api.company.com
    description: staging (always requires auth)
  - url: https://localhost:5001/
    description: local dev/test server with tls
  - url: http://localhost:5000/
    description: local dev/test server
```

... and turn it into something like this?

```yaml
environments:
  - url: https://staging.api.company.com
    description: staging (always requires auth)
    tag: staging
  - url: https://localhost:5001/
    description: local dev/test server with tls
    tag: localhost-https
  - url: http://localhost:5000/
    description: local dev/test server
    tag: localhost
```

Would we want to extend it further to enable multiple-API support? Something like:

```yaml
apis:
  name: products
    environments:
      - url: https://staging.api.company.com
        description: staging (always requires auth)
        tag: staging
      - url: https://localhost:5001/
        description: local dev/test server with tls
        tag: localhost-https
      - url: http://localhost:5000/
        description: local dev/test server
        tag: localhost
```
